#Project Euler, Problem 29
#Ardeshir Mostofi
#9/9/2014

#How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?

f = []

for a in xrange(2,101):
	for b in range(2,101):
		f.append(a ** b)

print len(set(f))
print '--'
print len(set(a ** b for a in range(2,101) for b in range(2,101)))